##########################################################
###################  测试环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://106.12.15.116:3306/community_xq?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 5

  redis:
    host: 118.24.224.186
    port: 6379
    password: cqpolice

projectPath: //data/demo/api