##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  datasource:
    url: jdbc:mysql://59.83.229.157:3306/community_xq?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: B3tUUFLTyvSR!
    druid:
      initial-size: 5

  redis:
    host: 118.24.224.186
    port: 6379
    password: cqpolice

logging:
  level:
    root: info
    druid.sql.Statement: debug
    com.cnaidun: debug


projectPath: C:\\gab_tmp